### ISSUE TITLE
Bot can't search text with multiple results

### ISSUE THREAD

**Issue by vintury** [AstralRomance/MtGCommanderBot#8]
**Describe the bug**
if you enter text that can be found in multiple cards, there will be no result.

**To Reproduce**
Search: "Triome"
Result: "Ivalid input or Scryfall troubles"

**Expected behavior**
Full text search with multiple results.
Example:
Search: "Triom"
Result: 

> Maybe you want: 
> Indatha Triome #iko
> Ketria Triome #iko
> Raugrin Triome #iko
> Savai Triome #iko
> Zagoth Triome #iko
> 

After select one of this, bot show detailed information:

> Zagoth Triome
> Ikoria: Lair of Behemoths
>     Near Mint: $11.99
> Ikoria: Lair of Behemoths (Foil)
>     Near Mint: $14.99
> Ikoria: Lair of Behemoths - Variants
>     Near Mint: $12.99
> Ikoria: Lair of Behemoths - Variants (Foil)
>     Near Mint: $34.99
> Promo: Date Stamped (Foil)
>     Near Mint: $14.99
> Promo: Planeswalker Stamped
>     Near Mint: $10.99
> Promo: Planeswalker Stamped (Foil)
>     Near Mint: $14.99
>

**Comment by AstralRomance** [comment]
Fixed with 4371805e3b825c4247bc1aa30769d8e7ac9649f7
